### ISSUE TITLE
Code and doc for g:fullscreen#enable_default_keymap not in sync

### ISSUE THREAD

**Issue by kazarmy** [lambdalisue/vim-fullscreen#5]
The configuration setting for enabling the default mapping is [g:fullscreen#enable_default_keymap](https://github.com/lambdalisue/vim-fullscreen/blob/0551a4930479bf85c76c28f8aeeb7e9f0a4eb3ec/plugin/fullscreen.vim#L20) and not `g:fullscreen#enable_default_keymaps` as stated in the documentation (lines [57](https://github.com/lambdalisue/vim-fullscreen/blob/0551a4930479bf85c76c28f8aeeb7e9f0a4eb3ec/doc/vim-fullscreen.txt#L57) and [146](https://github.com/lambdalisue/vim-fullscreen/blob/0551a4930479bf85c76c28f8aeeb7e9f0a4eb3ec/doc/vim-fullscreen.txt#L146)). I prefer `g:fullscreen#enable_default_keymap` (without the 's') since there is only one mapping and as a bonus, I don't have to change my `vimrc`.

**Comment by lambdalisue** [comment]
Thanks. Now it's fixed. https://github.com/lambdalisue/vim-fullscreen/blob/master/doc/vim-fullscreen.txt#L146

**Comment by kazarmy** [comment]
For completeness' sake, it's probably best to also fix line [57](https://github.com/lambdalisue/vim-fullscreen/blob/cbba08424c506deba4c0711e5de78b9a9a93b8c5/doc/vim-fullscreen.txt#L57) and [147](https://github.com/lambdalisue/vim-fullscreen/blob/cbba08424c506deba4c0711e5de78b9a9a93b8c5/doc/vim-fullscreen.txt#L147) but a competent person should be able to make correct conclusions from the documentation as it is now.

**Comment by lambdalisue** [comment]
Done. Thanks
