### ISSUE TITLE
Illegal character <C>: guioptions+=C

### ISSUE THREAD

**Issue by avysk** [lambdalisue/vim-fullscreen#8]
If I run `:FullscreenStart' on Windows, I see the following error message:

```
Error detected while processing function fullscreen#start[12]...fullscreen#emulator#start:
E539: Illegal character <C>: guioptions+=C
```

Very much the same thing happens on FreeBSD if wmctrl is not installed.

Indeed, `fullscreen#emulator#start` tries to add `C` to `guioptions`, and indeed this option does not exist; vim 9.0.1668.

**Comment by lambdalisue** [comment]
Thanks. You are right. I couldn't find `C` in `guioptions` either even in Vim 7.4 ([ref](https://github.com/vim/vim/blob/3b1db36689ee9b3a49de1362c1678372263a01fe/runtime/doc/options.txt#L3600-L3711)) so I just removed that in #9. Could you try it?

**Comment by avysk** [comment]
I have manually removed mentions of `C` guioption from autoload file and I think it works okay now.
